$(document).ready(function(){
	$("#search").click(function(){
		$("#search").hide();
		$("#query").removeAttr("display");
		$("#query").show();
		//display search bar
	})
	
	$("#query").keyup(function(event){
		if(event.keyCode === 13){
			//'enter' is pressed
			$("#results").empty();
			//#results cleared if there is already a search
			var request = document.getElementById("query").value;
			//load JSON-encoded data from server via a GET HTTP request based on query value
			$.getJSON("https://en.wikipedia.org/w/api.php?format=json&action=opensearch&search=" + request + "&origin=*&callback=?", function(data){
				getLink(data);
			})
		}
	})
});

function getLink(data){
	//variables assigned to various points of data generated by opensearch action (see api sandbox for example & clarification)
	var title = data[1];
	var description = data[2];
	var link = data[3];
	for(i = 0; i < data[3].length; i++){
		var pgDescription = '<a class="pgLink" href="' + link[i] + '"><h3>' + title[i] + '</h3><h4>' + description[i] + '</h4></a>';
		$("#results").append(pgDescription);
	}
	//10 search results are automatically generated by the opensearch action, so we simply loop through each one to display content
};
